### PR TITLE
EZP-31311: [Travis] Added job running browser tests

### PR DESCRIPTION
**Pull request by mnocon**
JIRA: https://jira.ez.no/browse/EZP-31311

As promised in https://github.com/ezsystems/ezplatform-query-fieldtype/pull/26 😉 
This PR adds a job running simple browser tests using Query Fieldtype in AdminUI.

### CODE REVIEW

**Comment by bdunogier** [comment]
Where are the tests themselves ?

**Comment by mnocon** [comment]
There are two Scenarios in AdminUI: https://github.com/ezsystems/ezplatform-admin-ui/blob/master/features/standard/ContentTypeFields.feature#L96

**Comment by bdunogier** [comment]
Thank you.

**Comment by mnocon** [comment]
@bdunogier are you ok with these changes, can we merge this?

**Comment by bdunogier** [comment]
Yes, @mnocon. Can you take care of merging ?

**Pull request merged**
