### PR TITLE
EZP-31675: do not cast parameters part to string

### PR DESCRIPTION
**Pull request by bdunogier**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31675](https://jira.ez.no/browse/EZP-31675)
| **Type**                                   | bug
| **Target eZ Platform version** | `v2.x`, `v3.x`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no

Due to a `string` typehint in the Query Field Service, integer or boolean parameters always ended up as strings, causing errors in the Query Types options resolution.

#### Checklist:
- [x] PR description is updated.
- [ ] Tests are implemented.
- [x] Added code follows Coding Standards (use `$ composer fix-cs`).
- [x] PR is ready for a review.

### CODE REVIEW

**Comment by bdunogier** [comment]
Good idea, @Nattfarinn, thank you.

**Comment by bdunogier** [comment]
@Nattfarinn is it better now ?

**Comment by bdunogier** [comment]
Thank you for the review & review-request, @Nattfarinn.

**Comment by lserwatka** [comment]
@adamwojs could you merge it up?

**Pull request merged**
