### PR TITLE
Merge 1.0 into 2.0

### PR DESCRIPTION
**Pull request by bdunogier**
For CI to run on.

### CODE REVIEW

**Comment by bdunogier** [comment]
Had to hotfix a stupid error that somehow evaded us during review (https://github.com/ezsystems/ezplatform-query-fieldtype/pull/44/commits/43da4efd9389b9318c42798403982eb23fea9c6b). Confidence level: 100%.

**Comment by lserwatka** [comment]
@bdunogier will you add it to 1.0 as well?

**Comment by bdunogier** [comment]
> @bdunogier will you add it to 1.0 as well?

As a matter of fact I already have 😓

**Comment by bdunogier** [comment]
Manually tested with a custom offset, and fixed CS in the last commit. We should be good soon. Some QA will be needed on the new features :)

**Comment by lserwatka** [comment]
Yes, but after beta tag. It is on the QA list. You can merge it.

**Comment by bdunogier** [comment]
I'll merge it as soon as travis is green, just to be safe. Shouldn't take long.

**Comment by bdunogier** [comment]
@lserwatka merged.

**Pull request merged**
