### PR TITLE
Render based on the current location (GraphQL v3)

### PR DESCRIPTION
**Pull request by bdunogier**

### CODE REVIEW

**Comment by dabrt** [comment]
Bon jour!
Does this PR require documentation?
Does it relate to EZP-31659 only, or there are other dependencies?
What product versions does it affect (will be merged to)?

**Comment by bdunogier** [comment]
> Does it relate to EZP-31659 only
Yes, besides the small change to admin-ui where we pass the location when rendering fields (so that we know what location is the current one).

It also depends on the future 3.0 version of the GraphQL package, that introduces advanced location & siteaccess handling.

>  Does this PR require documentation?
Yes, it does. I will complete the pull-request, sorry about that :)

>  What product versions does it affect (will be merged to)?
The goal is to merge it to the next major version of the package (2.0), and tag it as a beta version that can be installed on top of the LTS version.

**Comment by dabrt** [comment]
> Yes, it does. I will complete the pull-request, sorry about that :)

Merci!

**Comment by bdunogier** [comment]
I need to go a bit deeper into it, but this is still valid, as far as I can tell (it is a follow-up to the "better location handling" story).

**Pull request closed without merging**
